### ISSUE TITLE
Implement Basic Search API

### ISSUE THREAD

**Issue by FlatBallFlyer** [agile-learning-institute/mentorHub-search-api#4]
Our Search API should provide a polymorphic list of index cards, support a paginated scroll. The default query should be based on current date-time and the user-roles of the person making the request. A plain text search for any card with the provided text is MVP. 

NOTE: Research how OpenSearch Kibana might be used to support this service

**Comment by MyNameIsAndrew-Mangix** [comment]
Searches based on names, supporting partials. Still needs:
- Default query
- Pagination
